random_state:
  seed: 

descriptor:
  type: rdc
  params:
    r_min: 0.0
    r_max: 6.0
    dr: 0.05
    alpha: 10.0

spectrum_transformer:
  type: xanes
  params:
    e_min: -30.0
    e_max: 120.0
    n_bins: 300
    scale: True
    convolve: True
    convolution_params:
      conv_type: arctangent_model
      width: 2.0
      width_max: 15.0
      ef: -5.0
      ec: 30.0
      el: 30.0

feature_selection:
  threshold: 0.0

feature_scaling:
  with_mean: True
  with_std: True
      
model:
  hidden_layer_sizes:
    - 512
    - 512
  activation: relu
  solver: adam
  alpha: 0.0001
  batch_size: auto
  learning_rate: constant
  learning_rate_init: 0.001
  max_iter: 512

kfold:
  n_splits: 3
  n_repeats: 2

metric:
  type: mse