random_state:
  seed: 

descriptor:
  type: wacsf
  params:
    r_min: 0.0
    r_max: 6.0
    n_g2: 32
    n_g4: 64
    z:
      - 1
      - 2
      - 4
      - 8

spectrum_transformer:
  type: xanes
  params:
    energy_min: -15.0
    energy_max: 60.0
    n_bins: 226
    shift: 0.0
    scale: 1.0
    normalise: True
    conv: True
    conv_params:
      conv_type: arctangent
      width: 1.0
      width_max: 15.0
      ef: -1.0
      ec: 30.0
      el: 30.0

feature_selection:
  threshold: 0.0

feature_scaling:
  with_mean: True
  with_std: True
      
model:
  params:
    hidden_layer_sizes:
      - 512
      - 512
    activation: relu
    solver: adam
    alpha: 1.0E-4
    batch_size: 32
    learning_rate: constant
    learning_rate_init: 1.0E-3
    max_iter: 512

kfold:
  n_splits: 5
  n_repeats: 2

metric:
  type: mse